In [255]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [256]:
df = pd.read_csv('matches.csv')

In [257]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [258]:
df.head(10)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
1,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
2,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
3,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
4,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City
5,2021-09-25,12:30,Premier League,Matchweek 6,Sat,Away,W,1.0,0.0,Chelsea,...,Match Report,NaN,15.0,3.0,16.5,0.0,0.0,0.0,2022,Manchester City
6,2021-10-03,16:30,Premier League,Matchweek 7,Sun,Away,D,2.0,2.0,Liverpool,...,Match Report,NaN,12.0,3.0,16.8,1.0,0.0,0.0,2022,Manchester City
7,2021-10-16,15:00,Premier League,Matchweek 8,Sat,Home,W,2.0,0.0,Burnley,...,Match Report,NaN,16.0,6.0,14.6,0.0,0.0,0.0,2022,Manchester City
8,2021-10-23,17:30,Premier League,Matchweek 9,Sat,Away,W,4.0,1.0,Brighton,...,Match Report,NaN,23.0,13.0,15.7,1.0,0.0,0.0,2022,Manchester City
9,2021-10-30,15:00,Premier League,Matchweek 10,Sat,Home,L,0.0,2.0,Crystal Palace,...,Match Report,NaN,14.0,3.0,17.0,0.0,0.0,0.0,2022,Manchester City

In [259]:
df.shape

(1389, 27)

In [260]:
df["team"].value_counts()

team
Southampton                 72
Brighton and Hove Albion    72
Manchester United           72
West Ham United             72
Newcastle United            72
Burnley                     71
Leeds United                71
Crystal Palace              71
Manchester City             71
Wolverhampton Wanderers     71
Tottenham Hotspur           71
Arsenal                     71
Leicester City              70
Chelsea                     70
Aston Villa                 70
Everton                     70
Liverpool                   38
Fulham                      38
West Bromwich Albion        38
Sheffield United            38
Brentford                   34
Watford                     33
Norwich City                33
Name: count, dtype: int64

In [261]:
df["round"].value_counts()

round
Matchweek 1     39
Matchweek 16    39
Matchweek 34    39
Matchweek 32    39
Matchweek 31    39
Matchweek 29    39
Matchweek 28    39
Matchweek 26    39
Matchweek 25    39
Matchweek 24    39
Matchweek 23    39
Matchweek 2     39
Matchweek 19    39
Matchweek 17    39
Matchweek 20    39
Matchweek 15    39
Matchweek 5     39
Matchweek 3     39
Matchweek 13    39
Matchweek 12    39
Matchweek 4     39
Matchweek 11    39
Matchweek 10    39
Matchweek 9     39
Matchweek 8     39
Matchweek 14    39
Matchweek 7     39
Matchweek 6     39
Matchweek 30    37
Matchweek 27    37
Matchweek 22    37
Matchweek 21    37
Matchweek 18    37
Matchweek 33    32
Matchweek 35    20
Matchweek 36    20
Matchweek 37    20
Matchweek 38    20
Name: count, dtype: int64

In [262]:
df.isnull().sum()

date               0
time               0
comp               0
round              0
day                0
venue              0
result             0
gf                 0
ga                 0
opponent           0
xg                 0
xga                0
poss               0
attendance       696
captain            0
formation          0
referee            0
match report       0
notes           1389
sh                 0
sot                0
dist               1
fk                 0
pk                 0
pkatt              0
season             0
team               0
dtype: int64

In [263]:
df.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [264]:
df['date']= pd.to_datetime(df["date"])

In [265]:
df["venue_code"]= df['venue'].astype('category').cat.codes

In [266]:
df['opp_code']= df['opponent'].astype('category').cat.codes

In [267]:
df['hour']= df['time'].str.replace(":.+","",regex =True).astype('int')

In [268]:
df["day_code"] = df['date'].dt.dayofweek

In [269]:
df.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,dist,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code
0,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,16.9,1.0,0.0,0.0,2022,Manchester City,0,18,16,6
1,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,17.3,1.0,0.0,0.0,2022,Manchester City,1,15,15,5
2,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,14.3,0.0,0.0,0.0,2022,Manchester City,1,0,12,5
3,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,14.0,0.0,0.0,0.0,2022,Manchester City,0,10,15,5
4,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,15.7,1.0,0.0,0.0,2022,Manchester City,1,17,15,5

In [270]:
df['target'] = (df['result'] == 'W').astype('int')

In [271]:
#training a model
from sklearn.ensemble import RandomForestClassifier

In [272]:
rf = RandomForestClassifier(n_estimators = 50, min_samples_split=10, random_state=1)

In [273]:
train = df[df['date']<'2022-01-01']
test = df[df['date']>='2022-01-01']

In [274]:
predictors = ['venue_code','opp_code','hour','day_code']

In [275]:
rf.fit(train[predictors], train['target'])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [276]:
preds = rf.predict(test[predictors])

In [277]:
from sklearn.metrics import accuracy_score, precision_score

In [278]:
acc = accuracy_score(test['target'], preds)
print(acc)

0.6134751773049646

In [279]:
combined = pd.DataFrame(dict(actual = test['target'], prediction = preds ))

In [280]:
pd.crosstab(index = combined['actual'], columns = combined['prediction'])

prediction    0   1
actual
0           144  31
1            78  29

In [281]:
precision_score(test['target'], preds)

0.48333333333333334

In [282]:
grouped_matches = df.groupby('team')

In [283]:
group = grouped_matches.get_group('Chelsea')

In [284]:
def rolling_averages(group , cols , new_cols):
    group = group.sort_values('date')
    rolling_stats = group[cols].rolling(3, closed = 'left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset = new_cols)
    return group

In [285]:
cols = ['gf','ga','sh','sot','dist','fk','pk','pkatt']
new_cols = [f"{c}_rolling"for c in cols]
rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
746,2020-10-03,12:30,Premier League,Matchweek 4,Sat,Home,W,4.0,0.0,Crystal Palace,...,5,1,2.000000,2.000000,12.333333,5.666667,20.366667,0.666667,0.333333,0.666667
747,2020-10-17,15:00,Premier League,Matchweek 5,Sat,Home,D,3.0,3.0,Southampton,...,5,0,2.333333,1.666667,14.333333,5.666667,18.933333,0.666667,0.666667,1.000000
748,2020-10-24,17:30,Premier League,Matchweek 6,Sat,Away,D,0.0,0.0,Manchester Utd,...,5,0,3.333333,2.000000,17.000000,6.666667,15.300000,0.666667,0.666667,0.666667
749,2020-10-31,15:00,Premier League,Matchweek 7,Sat,Away,W,3.0,0.0,Burnley,...,5,1,2.333333,1.000000,11.000000,3.333333,15.300000,0.000000,0.666667,0.666667
750,2020-11-07,17:30,Premier League,Matchweek 8,Sat,Home,W,4.0,1.0,Sheffield Utd,...,5,1,2.000000,1.000000,10.666667,5.000000,15.733333,0.333333,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,2022-03-13,14:00,Premier League,Matchweek 29,Sun,Home,W,1.0,0.0,Newcastle Utd,...,6,1,2.666667,0.333333,12.000000,5.000000,15.600000,0.666667,0.000000,0.000000
61,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Home,L,1.0,4.0,Brentford,...,5,0,2.666667,0.333333,11.333333,5.000000,15.133333,0.666667,0.000000,0.000000
62,2022-04-09,15:00,Premier League,Matchweek 32,Sat,Away,W,6.0,0.0,Southampton,...,5,1,1.666667,1.666667,14.666667,6.000000,16.100000,0.666667,0.000000,0.000000
63,2022-04-20,19:45,Premier League,Matchweek 25,Wed,Home,L,2.0,4.0,Arsenal,...,2,0,2.666667,1.333333,17.666667,8.333333,17.000000,0.333333,0.000000,0.000000
64,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Home,W,1.0,0.0,West Ham,...,6,1,3.000000,2.666667,18.666667,8.000000,17.133333,0.000000,0.000000,0.000000

In [286]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [287]:
rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
746,2020-10-03,12:30,Premier League,Matchweek 4,Sat,Home,W,4.0,0.0,Crystal Palace,...,5,1,2.000000,2.000000,12.333333,5.666667,20.366667,0.666667,0.333333,0.666667
747,2020-10-17,15:00,Premier League,Matchweek 5,Sat,Home,D,3.0,3.0,Southampton,...,5,0,2.333333,1.666667,14.333333,5.666667,18.933333,0.666667,0.666667,1.000000
748,2020-10-24,17:30,Premier League,Matchweek 6,Sat,Away,D,0.0,0.0,Manchester Utd,...,5,0,3.333333,2.000000,17.000000,6.666667,15.300000,0.666667,0.666667,0.666667
749,2020-10-31,15:00,Premier League,Matchweek 7,Sat,Away,W,3.0,0.0,Burnley,...,5,1,2.333333,1.000000,11.000000,3.333333,15.300000,0.000000,0.666667,0.666667
750,2020-11-07,17:30,Premier League,Matchweek 8,Sat,Home,W,4.0,1.0,Sheffield Utd,...,5,1,2.000000,1.000000,10.666667,5.000000,15.733333,0.333333,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,2022-03-13,14:00,Premier League,Matchweek 29,Sun,Home,W,1.0,0.0,Newcastle Utd,...,6,1,2.666667,0.333333,12.000000,5.000000,15.600000,0.666667,0.000000,0.000000
61,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Home,L,1.0,4.0,Brentford,...,5,0,2.666667,0.333333,11.333333,5.000000,15.133333,0.666667,0.000000,0.000000
62,2022-04-09,15:00,Premier League,Matchweek 32,Sat,Away,W,6.0,0.0,Southampton,...,5,1,1.666667,1.666667,14.666667,6.000000,16.100000,0.666667,0.000000,0.000000
63,2022-04-20,19:45,Premier League,Matchweek 25,Wed,Home,L,2.0,4.0,Arsenal,...,2,0,2.666667,1.333333,17.666667,8.333333,17.000000,0.333333,0.000000,0.000000
64,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Home,W,1.0,0.0,West Ham,...,6,1,3.000000,2.666667,18.666667,8.000000,17.133333,0.000000,0.000000,0.000000

In [288]:
matches_rolling = df.groupby('team').apply(lambda x: rolling_averages(x,cols,new_cols))

In [289]:
matches_rolling = matches_rolling.droplevel('team')

In [290]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
898,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,Sheffield Utd,...,6,1,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
899,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,Manchester City,...,5,0,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
900,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
901,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
902,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,2022-03-13,14:00,Premier League,Matchweek 29,Sun,Away,W,1.0,0.0,Everton,...,6,1,1.333333,1.000000,12.333333,3.666667,19.300000,0.000000,0.000000,0.000000
228,2022-03-18,20:00,Premier League,Matchweek 30,Fri,Home,L,2.0,3.0,Leeds United,...,4,0,1.666667,0.666667,12.333333,4.333333,19.600000,0.000000,0.000000,0.000000
229,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,1.0,Aston Villa,...,5,1,2.333333,1.000000,13.000000,5.333333,19.833333,0.000000,0.000000,0.000000
230,2022-04-08,20:00,Premier League,Matchweek 32,Fri,Away,L,0.0,1.0,Newcastle Utd,...,4,0,1.666667,1.333333,13.000000,5.000000,18.533333,0.000000,0.000000,0.000000
231,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Away,L,0.0,1.0,Burnley,...,6,0,1.333333,1.666667,10.000000,4.666667,17.633333,0.000000,0.000000,0.000000

In [291]:
matches_rolling.index = range(matches_rolling.shape[0])

In [292]:
def make_prediction(data, predictors):
    train = data[data['date']<'2022-01-01']
    test = data[data['date']>='2022-01-01']
    rf.fit(train[predictors], train['target'])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual = test['target'], prediction = preds ),index = test.index)
    precision = precision_score(test['target'], preds)
    return combined, precision

In [293]:
combined , precision = make_prediction(matches_rolling, (predictors + new_cols))

In [294]:
combined = combined.merge(matches_rolling[['date','team','opponent','result']], left_index = True, right_index = True)
combined.head()

    actual  prediction       date     team         opponent result
54       0           0 2022-01-01  Arsenal  Manchester City      L
55       0           0 2022-01-23  Arsenal          Burnley      D
56       1           0 2022-02-10  Arsenal           Wolves      W
57       1           0 2022-02-19  Arsenal        Brentford      W
58       1           1 2022-02-24  Arsenal           Wolves      W

In [295]:
class MissingDict(dict):
    __missing__ = lambda self , key : key

map_values = {"Brighton and Hove Albion": "Brighton",
               "Manchester United": "Manchester Utd", 
               "Newcastle United": "Newcastle Utd", 
               "Tottenham Hotspur": "Tottenham", 
               "West Ham United": "West Ham", 
               "Wolverhampton Wanderers": "Wolves"
}
mapping = MissingDict(**map_values)

In [296]:
mapping['Wolverhampton Wanderers']

'Wolves'

In [297]:
combined['new_teams'] = combined['team'].map(mapping)
combined

,actual,prediction,date,team,opponent,result,new_teams
54,0,0,2022-01-01,Arsenal,Manchester City,L,Arsenal
55,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal
56,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal
57,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal
58,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal
...,...,...,...,...,...,...,...
1312,1,0,2022-03-13,Wolverhampton Wanderers,Everton,W,Wolves
1313,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,L,Wolves
1314,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W,Wolves
1315,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L,Wolves
1316,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L,Wolves

In [298]:
merged = combined.merge(combined , left_on=['date','new_teams'], right_on = ['date','opponent'])

In [301]:
merged

,actual_x,prediction_x,date,team_x,opponent_x,result_x,new_teams_x,actual_y,prediction_y,team_y,opponent_y,result_y,new_teams_y
0,0,0,2022-01-01,Arsenal,Manchester City,L,Arsenal,1,0,Manchester City,Arsenal,W,Manchester City
1,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
2,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
3,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
4,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,1,0,2022-03-13,Wolverhampton Wanderers,Everton,W,Wolves,0,0,Everton,Wolves,L,Everton
264,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,L,Wolves,1,0,Leeds United,Wolves,W,Leeds United
265,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W,Wolves,0,0,Aston Villa,Wolves,L,Aston Villa
266,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L,Wolves,1,0,Newcastle United,Wolves,W,Newcastle Utd
267,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L,Wolves,1,0,Burnley,Wolves,W,Burnley

In [303]:
merged[merged['prediction_x']==1 & (merged['prediction_y'] == 0 )]['actual_x'].value_counts()

actual_x
0    45
1    35
Name: count, dtype: int64